version: '3.8'

services:
  # Serviço do Banco de Dados PostgreSQL
  db:
    image: postgres:16-alpine  # Imagem oficial do Postgres, leve (versão 16)
    container_name: agendaflow_db
    restart: always
    ports:
      - "5432:5432"  # Expõe a porta 5432 do contêiner para a sua máquina
    environment:
      # Essas variáveis vêm do arquivo .env na raiz
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data # Persiste os dados do banco
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: # Define o volume que será usado para persistir os dados